[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# non-WWW to WWW redirect (only for non-sitemap URLs)
[[redirects]]
  from = "https://saveearnshare.com/*"
  to = "https://www.saveearnshare.com/:splat"
  status = 301
  force = true
  conditions = {Path = {not = ["/sitemap.xml"]}}

# HTTP to HTTPS redirect (only for non-sitemap URLs)
[[redirects]]
  from = "http://:domain/*"
  to = "https://:domain/:splat"
  status = 301
  force = true
  conditions = {Path = {not = ["/sitemap.xml"]}}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.saveearnshare.com; img-src 'self' data: https:; font-src 'self' data: https:; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; connect-src 'self' https:; frame-ancestors 'none';"
